# Generated by Django 2.2.25 on 2022-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELC', 'Electronics'), ('UNI', 'Unique Items'), ('RES', 'Real Estate'), ('VEH', 'Vehicles'), ('OTH', 'Others')], max_length=20),
        ),
    ]
