# Generated by Django 2.2.25 on 2022-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221213_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='a_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
